# Sidebar navigation

- label: 'トップ'
  link: '/'
- label: 'Flutterとは'
  items:
    - label: 'Flutter概要'
      link: '/introduction/about-flutter'
- label: 'Flutterを使ってみる'
  items:
    - label: 'インストール'
      link: '/getting-started/install'
    - label: 'エディタ設定'
      link: '/getting-started/editor'
    - label: 'アプリ起動'
      link: '/getting-started/run-app'
- label: 'Widgetを使ってみる'
  items:
    - label: 'Widgetとは'
      link: '/widgets/about-widget'
    - label: 'テキストを表示'
      link: '/widgets/text-widget'
    - label: 'サイズ・背景・余白・枠線'
      link: '/widgets/container-widget'
    - label: '縦・横に並べる'
      link: '/widgets/column-row-widget'
    - label: 'ボタンを表示'
      link: '/widgets/button-widget'
    - label: 'リストを表示'
      link: '/widgets/list-view-widget'
    - label: 'AppBarを表示'
      link: '/widgets/app-bar-widget'
    - label: '状態を持ったWidget'
      link: '/widgets/state-widget'
- label: 'Todoアプリを作ってみる'
  items:
    - label: 'Todoアプリ概要'
      link: '/todo-app/about-todo-app'
    - label: 'Todoリスト一覧画面'
      link: '/todo-app/list-page'
    - label: 'Todoリスト追加画面'
      link: '/todo-app/add-page'
- label: 'Firebaseとの連携'
  items:
    - label: 'Firebase概要'
      link: '/firebase/about-firebase'
    - label: 'Authenticationでログイン'
    - label: 'Firestoreでデータ保存'
- label: '少し複雑なアプリ作成'
  items:
    - label: 'Google認証でログイン'
    - label: 'Firestoreと連携'
    - label: 'Providerで状態管理'
- label: '自分だけのWebアプリ公開'
  items:
    - label: 'Hosting概要'
    - label: 'Webアプリ公開'
- label: 'その他'
  items:
    - label: 'ご利用にあたって'
      link: '/about'