# Sidebar navigation

- label: 'トップ'
  link: '/'
- label: 'Flutterとは'
  items:
    - label: 'Flutter概要'
      link: '/introduction/about-flutter'
- label: 'Flutterを使ってみる'
  items:
    - label: 'インストール'
      link: '/getting-started/install'
    - label: 'エディタ設定'
      link: '/getting-started/editor'
    - label: 'アプリ起動'
      link: '/getting-started/run-app'
- label: 'Widgetを使ってみる'
  items:
    - label: 'Widgetとは'
      link: '/widgets/about-widget'
    - label: 'テキストを表示'
      link: '/widgets/text-widget'
    - label: 'サイズ・背景・余白・枠線'
      link: '/widgets/container-widget'
    - label: '縦・横に並べる'
    - label: 'ボタンを表示'
    - label: 'リストを表示'
    - label: 'AppBarを表示'
- label: 'Todoアプリを作ってみる'
  items:
    - label: '画面を切り替える'
    - label: 'Todoリストを入力'
    - label: 'Todoリストを保持'
    - label: 'Todoリストを表示'
- label: 'Firebaseとの連携'
  items:
    - label: 'Firebase概要'
    - label: 'Authenticationでログイン'
    - label: 'Firestoreでデータ保存'
- label: '少し複雑なアプリ作成'
  items:
    - label: 'Google認証でログイン'
    - label: 'Firestoreと連携'
    - label: 'Providerで状態管理'
- label: '自分だけのWebアプリ公開'
  items:
    - label: 'Hosting概要'
    - label: 'Webアプリ公開'
- label: 'その他'
  items:
    - label: 'ご利用にあたって'
      link: '/about'
- label: Usage
  items:
    - label: 'Creating docs'
      link: '/usage/creating-docs'
    - label: 'Navigation'
      link: '/usage/navigation'
    - label: 'Shadowing'
      link: '/usage/shadowing'