# Sidebar navigation
- label: 'Twitter'
  link: 'https://twitter.com/flutter_study'
- label: 'note'
  link: 'https://note.com/_umatoma'
- label: 'BOOTH'
  link: 'https://umatoma.booth.pm/items/2420736'
- label: 'MENTA'
  link: 'https://menta.work/plan/1947'
- label: 'トップ'
  link: '/'
- label: '1.Flutterとは'
  items:
    - label: 'Flutter概要'
      link: '/introduction/about-flutter'
- label: '2.Flutterを使ってみる'
  items:
    - label: 'インストール'
      link: '/getting-started/install'
    - label: 'エディタ設定'
      link: '/getting-started/editor'
    - label: 'アプリ起動'
      link: '/getting-started/run-app'
- label: '3.Widgetを使ってみる'
  items:
    - label: 'Widgetとは'
      link: '/widgets/about-widget'
    - label: 'テキストを表示'
      link: '/widgets/text-widget'
    - label: 'サイズ・背景・余白・枠線'
      link: '/widgets/container-widget'
    - label: '縦・横に並べる'
      link: '/widgets/column-row-widget'
    - label: 'ボタンを表示'
      link: '/widgets/button-widget'
    - label: 'リストを表示'
      link: '/widgets/list-view-widget'
    - label: 'AppBarを表示'
      link: '/widgets/app-bar-widget'
    - label: '状態を持ったWidget'
      link: '/widgets/state-widget'
- label: '4.Todoアプリを作ってみる'
  items:
    - label: 'Todoアプリ概要'
      link: '/todo-app/about-todo-app'
    - label: 'Todoリスト一覧画面'
      link: '/todo-app/list-page'
    - label: 'Todoリスト追加画面'
      link: '/todo-app/add-page'
- label: '5.Firebaseとは'
  items:
    - label: 'Firebase概要'
      link: '/firebase/about-firebase'
    - label: 'Authentication概要'
      link: '/firebase/authentication'
    - label: 'Firestore概要'
      link: '/firebase/cloud-firestore'
    - label: 'Firestoreを使ってみる'
      link: '/firebase/cloud-firestore-try'
- label: '6.Firebaseを使ったアプリ'
  items:
    - label: 'アプリ概要'
      link: '/firebase-app/about-firebase-app'
    - label: 'Authenticationでログイン'
      link: '/firebase-app/authentication'
    - label: 'Firestoreでデータ保存'
      link: '/firebase-app/firestore'
    - label: 'Firestoreでリアルタイム更新'
      link: '/firebase-app/firestore-stream'
    - label: 'Providerで状態管理'
      link: '/firebase-app/provider'
- label: '7.Webアプリ公開'
  items:
    - label: 'Hosting概要'
      link: '/host-web-app/hosting'
    - label: 'HostingでWebアプリ公開'
      link: '/host-web-app/host-web-app'
- label: 'UIを作ってみる'
  items:
    - label: 'UIを作ってみる'
      link: '/create-ui/top'
    - label: 'Admin Mobile'
      link: '/create-ui/admin-mobile'
    - label: 'Sign In / Sign Up'
      link: '/create-ui/sign-in-sign-up'
    - label: 'Battery Optimizer'
      link: '/create-ui/battery-optimizer'
    - label: 'Flight Booking'
      link: '/create-ui/flight-booking'
    - label: 'アニメーション基礎'
      link: '/create-ui/animation'
    - label: 'Online Learning'
      link: '/create-ui/online-learning'
- label: 'アプリを作ってみる'
  items:
    - label: 'アプリを作ってみる'
      link: '/create-app/top'
    - label: 'Providerで状態管理'
      link: '/create-app/provider'
    - label: '音楽・動画を再生する'
      link: '/create-app/media-player'
    - label: 'Androidアプリを公開する'
      link: '/create-app/publish-android'
    - label: 'Codemagicで自動化'
      link: '/create-app/codemagic'
    - label: 'Qiita App'
      link: '/create-app/qiita-app'
- label: 'Flutter詳細'
  items:
    - label: 'Flutter on the web'
      link: '/master-flutter/flutter-web'
- label: 'Widgetの使い方'
  items:
    - label: 'Scaffold'
      link: /master-widgets/scaffold
- label: 'その他'
  items:
    - label: 'ご利用にあたって'
      link: '/about'