# Sidebar navigation

- label: 'トップ'
  link: '/'
- label: 'Flutterとは'
  items:
    - label: 'Flutter概要'
      link: '/introduction/about-flutter'
- label: 'Flutterを使ってみる'
  items:
    - label: 'インストール'
      link: '/getting-started/install'
    - label: 'エディタ設定'
      link: '/getting-started/editor'
    - label: 'アプリ起動'
- label: 'Widgetを使ってみる'
  items:
    - label: 'テキストを表示する'
    - label: '背景色を変える'
    - label: '縦・横に並べる'
    - label: '余白を付ける'
    - label: 'ボタンを表示する'
    - label: 'リストを表示する'
    - label: 'AppBarを表示する'
- label: 'Todoアプリを作ってみる'
  items:
    - label: '画面を切り替える'
    - label: 'Todoリストを入力する'
    - label: 'Todoリストを保持する'
    - label: 'Todoリストを表示する'
- label: 'Firebaseとの連携'
  items:
    - label: 'Firebase概要'
    - label: 'Authenticationでログイン'
    - label: 'Firestoreでデータ保存'
- label: '少し複雑なアプリ作成'
  items:
    - label: 'Google認証でログイン'
    - label: 'Firestoreと連携'
    - label: 'Providerで状態管理'
- label: '自分だけのWebアプリ公開'
  items:
    - label: 'Hosting概要'
    - label: 'Webアプリ公開'
- label: 'その他'
  items:
    - label: 'ご利用にあたって'
      link: '/about'
- label: Usage
  items:
    - label: 'Creating docs'
      link: '/usage/creating-docs'
    - label: 'Navigation'
      link: '/usage/navigation'
    - label: 'Shadowing'
      link: '/usage/shadowing'