# Sidebar navigation

- label: 'トップ'
  link: '/'
- label: '1.Flutterとは'
  items:
    - label: 'Flutter概要'
      link: '/introduction/about-flutter'
- label: '2.Flutterを使ってみる'
  items:
    - label: 'インストール'
      link: '/getting-started/install'
    - label: 'エディタ設定'
      link: '/getting-started/editor'
    - label: 'アプリ起動'
      link: '/getting-started/run-app'
- label: '3.Widgetを使ってみる'
  items:
    - label: 'Widgetとは'
      link: '/widgets/about-widget'
    - label: 'テキストを表示'
      link: '/widgets/text-widget'
    - label: 'サイズ・背景・余白・枠線'
      link: '/widgets/container-widget'
    - label: '縦・横に並べる'
      link: '/widgets/column-row-widget'
    - label: 'ボタンを表示'
      link: '/widgets/button-widget'
    - label: 'リストを表示'
      link: '/widgets/list-view-widget'
    - label: 'AppBarを表示'
      link: '/widgets/app-bar-widget'
    - label: '状態を持ったWidget'
      link: '/widgets/state-widget'
- label: '4.Todoアプリを作ってみる'
  items:
    - label: 'Todoアプリ概要'
      link: '/todo-app/about-todo-app'
    - label: 'Todoリスト一覧画面'
      link: '/todo-app/list-page'
    - label: 'Todoリスト追加画面'
      link: '/todo-app/add-page'
- label: '5.Firebaseとは'
  items:
    - label: 'Firebase概要'
      link: '/firebase/about-firebase'
    - label: 'Authentication概要'
      link: '/firebase/authentication'
    - label: 'Firestore概要'
      link: '/firebase/cloud-firestore'
    - label: 'Firestoreを使ってみる'
      link: '/firebase/cloud-firestore-try'
- label: '6.Firebaseを使ったアプリ'
  items:
    - label: 'アプリ概要'
      link: '/firebase-app/about-firebase-app'
    - label: 'Authenticationでログイン'
      link: '/firebase-app/authentication'
    - label: 'Firestoreでデータ保存'
      link: '/firebase-app/firestore'
    - label: 'Firestoreでデータ同期'
    - label: 'Providerで状態管理'
- label: '7.自分だけのWebアプリ公開'
  items:
    - label: 'Hosting概要'
    - label: 'Webアプリ公開'
- label: 'その他'
  items:
    - label: 'ご利用にあたって'
      link: '/about'